import { Business, Category, Product, Order } from '@/lib/types/database';

export const MOCK_BUSINESS: Business = {
  id: 'b1010101-0000-0000-0000-000000000001',
  slug: 'panaderia-cuenca',
  nombre: 'Café & Panadería El Sagrario',
  ruc: '0104598123001',
  telefono_whatsapp: '593987654321',
  direccion: 'Calle Larga 8-23 y Luis Cordero, Cuenca',
  logo_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
  datos_bancarios: {
    banco: 'Banco Pichincha',
    tipo_cuenta: 'Ahorros',
    numero_cuenta: '2204589102',
    titular: 'María Carmen Torres',
    ruc_ci: '0104598123',
    email: 'pagos@elsagrario.ec',
  },
  zonas_envio: [
    { id: 'z1', zona: 'Centro Histórico / El Ejido', costo: 1.50 },
    { id: 'z2', zona: 'Totoracocha / Monay', costo: 2.00 },
    { id: 'z3', zona: 'Yanuncay / Baños', costo: 2.50 },
    { id: 'z4', zona: 'Challuabamba / Ricaurte', costo: 3.50 },
  ],
  payphone_token: 'mock-payphone-token-12345',
  plan: 'pro',
  created_at: new Date().toISOString(),
};

export const MOCK_CATEGORIES: Category[] = [
  { id: 'c1', business_id: MOCK_BUSINESS.id, nombre: '🔥 Tradición Cuencana', orden: 1, created_at: new Date().toISOString() },
  { id: 'c2', business_id: MOCK_BUSINESS.id, nombre: '☕ Cafetería Artesanal', orden: 2, created_at: new Date().toISOString() },
  { id: 'c3', business_id: MOCK_BUSINESS.id, nombre: '🥖 Pan horneado hoy', orden: 3, created_at: new Date().toISOString() },
  { id: 'c4', business_id: MOCK_BUSINESS.id, nombre: '🍰 Dulces & Postres', orden: 4, created_at: new Date().toISOString() },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    business_id: MOCK_BUSINESS.id,
    category_id: 'c1',
    nombre: 'Humita Criolla con Queso Amasado',
    descripcion: 'Humita de choclo tierno al vapor servida con tajada de queso fresco de hoja.',
    precio: 1.75,
    stock: 25,
    imagen_url: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=500&q=80',
    disponible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p2',
    business_id: MOCK_BUSINESS.id,
    category_id: 'c1',
    nombre: 'Tamal Cuencano Especial',
    descripcion: 'Tamal de maíz relleno de pollo, huevo duro, pasas y aderezo criollo envuelto en hoja de achira.',
    precio: 2.25,
    stock: 20,
    imagen_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&q=80',
    disponible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p3',
    business_id: MOCK_BUSINESS.id,
    category_id: 'c2',
    nombre: 'Café de Pasada Tradicional (Taza Grande)',
    descripcion: 'Café de altura lojano pasado en gota a gota con aroma intenso.',
    precio: 1.50,
    stock: 100,
    imagen_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&q=80',
    disponible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p4',
    business_id: MOCK_BUSINESS.id,
    category_id: 'c2',
    nombre: 'Capuchino Artesanal con Espuma de Leche',
    descripcion: 'Espresso doble con leche cremada y espolvoreado de canela de Vilcabamba.',
    precio: 2.50,
    stock: 50,
    imagen_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500&q=80',
    disponible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p5',
    business_id: MOCK_BUSINESS.id,
    category_id: 'c3',
    nombre: 'Pan de Agua Tradicional (Funda x 6)',
    descripcion: 'Pan crujiente recién salido del horno de leña.',
    precio: 1.20,
    stock: 40,
    imagen_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&q=80',
    disponible: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'p6',
    business_id: MOCK_BUSINESS.id,
    category_id: 'c4',
    nombre: 'Quesadilla Cuencana con Dulce de Guayaba',
    descripcion: 'Pastel tradicional de almidón de achira con relleno suave de queso y dulce.',
    precio: 1.80,
    stock: 15,
    imagen_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&q=80',
    disponible: true,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_INITIAL_ORDERS: Order[] = [
  {
    id: 'o-1001',
    business_id: MOCK_BUSINESS.id,
    numero_pedido: 48,
    cliente_nombre: 'Santiago Benalcázar',
    cliente_telefono: '0991234567',
    cliente_direccion: 'Av. Remigio Crespo y Imbabura, Dpto 3B',
    latitud: -2.902,
    longitud: -79.008,
    tipo_entrega: 'domicilio',
    numero_mesa: null,
    costo_envio: 1.50,
    subtotal: 7.00,
    total: 8.50,
    metodo_pago: 'payphone',
    estado_pago: 'pagado',
    comprobante_pago_url: null,
    payphone_transaction_id: 'PYP-894210',
    requiere_factura: true,
    datos_facturacion: {
      tipo_doc: 'RUC',
      num_doc: '0102938475001',
      razon_social: 'CORP BENALCAZAR S.A.',
      email: 'santiago@benalcazar.ec',
      direccion: 'Av. Remigio Crespo, Cuenca',
    },
    estado: 'pendiente',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'o-1002',
    business_id: MOCK_BUSINESS.id,
    numero_pedido: 47,
    cliente_nombre: 'Andrea Maldonado',
    cliente_telefono: '0987654321',
    cliente_direccion: 'Calle Gran Colombia 12-45',
    latitud: null,
    longitud: null,
    tipo_entrega: 'retiro_local',
    numero_mesa: null,
    costo_envio: 0,
    subtotal: 5.25,
    total: 5.25,
    metodo_pago: 'transferencia',
    estado_pago: 'verificando',
    comprobante_pago_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&q=80',
    payphone_transaction_id: null,
    requiere_factura: false,
    datos_facturacion: null,
    estado: 'aceptado',
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
];
